### ISSUE TITLE
Mouse Pointer always shows currently active tool when mouse pointer is over canvas

### ISSUE THREAD

**Issue by berndsalewski** [lospec/pixel-editor#63]
**Is your feature request related to a problem? Please describe.**
I find detecting the position of the mouse pointer when the background grid is activated quite hard. 

**Describe the solution you'd like**
always show the currently selected tool at mouse pointer position. Like you do for fill tool

**Additional context**
This is how it look with pen tool activated. not visible enough imho.\
![image](https://user-images.githubusercontent.com/1662484/143775772-0f2c0541-3ca1-4f1a-a54f-8d30d0887263.png)

even harder to read when zoomed in
![image](https://user-images.githubusercontent.com/1662484/143775957-17f00722-aa18-40c7-81cc-043a98c6576c.png)

**Comment by unsettledgames** [comment]
Hi! Thanks for this issue. We've improved the cursor in the new update, which should hopefully release in a few weeks / months. Since having a tool icon wasn't precise enough, we decided to make the brush preview have a shadow on the pixel the user is currently drawing on. We also made the editor adjust the thickness of the grid depending on the zoom level (so that you don't get a super thick grid when you zoomed in a lot). This is how the new cursor + grid is looking like.

![image](https://user-images.githubusercontent.com/47360416/143777370-5045ef5c-b753-4596-99ff-6bca4dc67e3e.png)

**Comment by unsettledgames** [comment]
Hey! I noticed that you've forked the main repo. If you plan on working on the code, please fork my fork instead, as it is the one used for development and the most up to date: https://github.com/unsettledgames/pixel-editor

**Comment by berndsalewski** [comment]
> Hey! I noticed that you've forked the main repo. If you plan on working on the code, please fork my fork instead, as it is the one used for development and the most up to date: https://github.com/unsettledgames/pixel-editor

thanks for the info. May I ask why this original repo is not used for active development? Was this one abandoned?

**Comment by unsettledgames** [comment]
We're going through a big refactoring of the editor, so a lot of code has changed and merging the conflicts on the main repo has become a bit time consuming, so I try to redirect people on my fork when I can. The refactoring is almost done though :)
